### ISSUE TITLE
Move it to nuxt-modules?

### ISSUE THREAD

**Issue by Atinux** [nuxt-modules/plausible#1]
Hey @johannschopplich 

We really like your module with the Nuxt team and actually are using it on nuxt.com.

Would you be up to move it to nuxt-modules organization? 😊

**Comment by johannschopplich** [comment]
Hey there, @Atinux,
thank you for the offer. Absolutely, it would be a pleasure!

How do we proceed? 🙂

**Comment by Atinux** [comment]
Hey @johannschopplich 

Two methods:
- Invite me and give me the owner access to I can transfer
- go to https://github.com/johannschopplich/nuxt-plausible/settings, click transfer at the bottom, and type in `nuxt-modules`

**Comment by johannschopplich** [comment]
I tried to move it to `nuxt-modules`, but: 
> You don’t have the permission to create public repositories on nuxt-modules.

So I've given you an invitation for ownership.

**Comment by Atinux** [comment]
It's live! https://github.com/nuxt-modules/plausible

I kept you as admin of the repo @johannschopplich ❤️

**Comment by johannschopplich** [comment]
Amazing. Thank you! 💚

**Comment by danielroe** [comment]
You should also have publish access to `@nuxtjs/plausible` 😁 Ping me if you'd like help updating https://github.com/nuxt/modules.
