### ISSUE TITLE
Could be initiated on demand

### ISSUE THREAD

**Issue by boudydegeer** [nuxt-modules/plausible#10]
Due to the GDPR in Europe, it would be nice to have a way to no auto initiate the plugin until the user accepts the GDPR/Cookie Consent. 

Is there a possibility to do it?

Should/Could I try to do a PR?

Thanks in advance

**Comment by johannschopplich** [comment]
As far as I understand it, Plausible is [GDPR-compliant by default](https://plausible.io/data-policy). That's the reason I choose it for my projects. 

Having said that, a `grantConsent` method might come in handy. I have implemented such in the [`nuxt-gtag`](https://github.com/johannschopplich/nuxt-gtag) module. Sure, PR welcome!

**Comment by Barbapapazes** [comment]
Yes, no cookies are used by Plausible and impossible to trace a user. It's GPDR compliant!
