### ISSUE TITLE
useTrackEvent not found

### ISSUE THREAD

**Issue by Suniron** [nuxt-modules/plausible#18]
Hello,

I'm trying to use `useTrackEvent` in my Nuxt package (which is based on Nuxt Module, inside my turborepo monorepo to be shared between my differents Nuxt3 apps).

I got this error: `Cannot find name 'useTrackEvent'.` in vscode but also in CLI.

How can i import this composable to fix the typing? From where?

Thank's in advance.

**Comment by johannschopplich** [comment]
Hi there! Thanks for the report. Can you please provide a reproducible example? Please use a template below to create a minimal reproduction:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Thanks in advance!

**Comment by johannschopplich** [comment]
Closing this as no reproduction was provided. If you run into the issue again, please open a new issue. Thanks!
