### ISSUE TITLE
Heads up: Plausible site verification tool

### ISSUE THREAD

**Issue by aerosol** [nuxt-modules/plausible#24]
Hey,

just wanted to notify you about a new feature we'll be soon introducing in Plausible - a site verification tool allowing you to verify the integration. 

It will employ a [headless agent](https://github.com/plausible/analytics/blob/master/priv/verification/verify_plausible_installed.js) that visits the site and seeks for `window.plausible()` function being defined. 

The signature is `plausible(eventName, options)` where `options` must be able to accept a `callback` key with a value of `function({status})` - status is the HTTP status of `/api/events` response. The agent will send a custom event using that function. Otherwise the verification will be marked as failing.

Our tracker [has been updated accordingly](https://github.com/plausible/analytics/blob/c15ce1fa154f1226f07c3abddc77727d236c01d9/tracker/src/plausible.js#L118), as well as the [npm package](https://github.com/plausible/plausible-tracker/commit/2dc3dcffe519e49656b8327f975a4e68d5478f56). If you like the nuxt module to be verifiable, please consider applying similar changes.

Many thanks!

**Comment by Bcdo** [comment]
This is related to the plausible integration not finding the Plausible snippet. I have followed the documentation for the integration, but Plausible seems to struggle with detecting the "snippet", which I guess gets auto-injected by the module?

**Comment by aerosol** [comment]
@Bcdo yup, since there is no snippet and no support for the callback I mentioned, our headless browser test can't tell if the test event was sent, thus making verification fail.

**Comment by Bcdo** [comment]
Is there a workaround? Or do I need to install it manually outside the module for now?

**Comment by johannschopplich** [comment]
There is no workaround at the moment, because this package no longer uses the official `plausible-tracker' package, which seems to have been abandoned years ago. Instead, we use a maintained [Plausible tracker rewrite](https://github.com/Barbapapazes/plausible-tracker) by @Barbapapazes.

**Comment by Barbapapazes** [comment]
Is there any documentation page related to this new feature?

**Comment by aerosol** [comment]
@Barbapapazes hi, what sort of documentation do you require? I described the implementation details in the top post of this thread. Let me know if anything's unclear. Thanks.

**Comment by Barbapapazes** [comment]
After reading it again, I think it's clear. I will update my fork accordingly.

**Comment by Barbapapazes** [comment]
Hey, could you tell me if I well understand the site verification process? Thanks 🙌

https://github.com/Barbapapazes/plausible-tracker/pull/14

**Comment by Barbapapazes** [comment]
> Hey, could you tell me if I well understand the site verification process? Thanks 🙌
> 
> https://github.com/Barbapapazes/plausible-tracker/pull/14/files#diff-fb108acf4e2165bea92e646b4d968ae7fd3c9b649376478cc8aa79f7be2966d3R9

Merged
