### ISSUE TITLE
How to capture fetch errors?

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-modules/plausible#28]
I'm getting a lot of `TypeError: Failed to fetch` in Sentry from failing Plausible fetch requests:

<img width="896" alt="Screenshot 2024-07-11 at 22 43 22" src="https://github.com/user-attachments/assets/117aff8d-f88d-4611-be37-b976599ea1c8">

I tried wrapping the `useTrackEvent` composable into a try/catch like so:

<img width="913" alt="Screenshot 2024-07-11 at 22 42 52" src="https://github.com/user-attachments/assets/22dcc008-56c1-4907-9352-b5643797136f">

But the events still get logged and spam Sentry.

Not sure why exactly the requests to the Plausible API fail, but is there a way to properly catch/handle/ignore them?

Might be an upstream issue in plausible-tracker?

**Comment by johannschopplich** [comment]
We're not using the Plausible tracker package anymore, since it has been abandoned for years. Instead, we use [a fork by](https://github.com/Barbapapazes/plausible-tracker) @Barbapapazes. Maybe he can tell use more why wrapping the composable won't catch a failing `fetch` promise? 👀

**Comment by Barbapapazes** [comment]
Hello 👋,

It's related to this function https://github.com/Barbapapazes/plausible-tracker/blob/main/src/event.ts#L72

Do you think I should add a `.catch` and let the dev passing a callback to handle it?

**Comment by Barbapapazes** [comment]
And @toniengelhardt, I think the `try...catch` does not work because I do not `await` the event

**Comment by Barbapapazes** [comment]
Do you know if every request change or if it is only some of them (like someone using a blocker) or does Plausible change something to their API?

**Comment by toniengelhardt** [comment]
@johannschopplich @Barbapapazes thanks for investigating 🙏🏽

Only very few events fail – not sure if bc of a blocker or bc the Plausible API drops them for some reason – but with a couple thousand events this still leads to quite some noise in Sentry (and unfortunately fetch errors are hard to decipher there).

For me, awaiting the event would make a lot of sense, so that wrapping the composable like in the example would work. But it might be also useful to be able to pass an error handler, ideally globally in the config and directly in the `useTrackEvent` composable in case it is only needed occasionally. 

A `failSilently` flag would also work, but is probably the most limiting solution. 

Any of the above would work for my use case as long as I can somehow prevent errors from being thrown.

**Comment by Barbapapazes** [comment]
I will need to tackle this in my fork because there `trackEvent` does not return a promise.

**Comment by Barbapapazes** [comment]
related to https://github.com/Barbapapazes/plausible-tracker/issues/11

**Comment by toniengelhardt** [comment]
Thanks @Barbapapazes 🙏🏽

**Comment by Barbapapazes** [comment]
You can follow the progression with this PR: https://github.com/Barbapapazes/plausible-tracker/pull/13

**Comment by Barbapapazes** [comment]
Test have been merged, I can now fix this issue.

**Comment by johannschopplich** [comment]
This should be resolved with the latest version v1.0.1, which uses the latest version of @Barbapapazes's tracker library. Thanks for the updates!
