### ISSUE TITLE
proxyBaseURL is not set correctly, always goes to /api/event + cant be overwritten

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/plausible#37]
- The docs state that when setting `proxy: true` the requests go to: `/api/__plausible_event__` but they go to `/api/event`
- Further, when setting `proxyBaseURL` manually it has no effect, they still go to `/api/event`

Reproduction repo: https://github.com/MickL/plausible-proxy-bug
(You can see it in the network tab)

**Comment by MickL** [comment]
I even get an error:

> POST https://www.../api/event 404 (Not Found)

**Comment by johannschopplich** [comment]
Thanks for the report!
