### ISSUE TITLE
proxyBaseURL default should not start with `/api`

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/plausible#38]
IMO the default proxy path should not start with `/api` because this might conflict with existing paths or existing proxy rules. E.g. I proxy everything that starts with '/api' to my external API.

I use a lot of modules in my project and none is using the '/api' prefix so I never had a problem until now. E.g. nuxt-icon uses /_nuxt_icon, nuxt-images goes to /_ipx for ipx provider.

Following the consistency of other modules, my suggestion would be to change the default to `/_plausible_event`

**Comment by johannschopplich** [comment]
I don't think that's the right way to do this. IMHO, Nuxt Icon also uses the `/api` path:

https://github.com/nuxt/icon/blob/1381039a295dd73681e46cb54af45892bb51c3ca/src/module.ts#L82

**Comment by johannschopplich** [comment]
OK, got it. Let' use `_plausible` as a base. If a user requires the API prefix, he can still add it:

```ts
export default defineNuxtConfig({
  plausible: {
    proxy: true,
    proxyBaseEndpoint: '/api/_plausible',
  },
})
```

**Comment by johannschopplich** [comment]
Fixed in https://github.com/nuxt-modules/plausible/commit/1e229ac66ffe14cbf4d3973ced004bcf2f43ee16.

**Comment by MickL** [comment]
Thanks for the quick fix! Just one note: It is now `_plausible/api/event` instead of `_plausible/event` :D

**Comment by johannschopplich** [comment]
Yes, this is intended. The Plausible Tracker library will always call `api/event`. But what we can do, is change the API host. That's what the proxy is for.

**Comment by MickL** [comment]
I see, thanks for the info!
