### ISSUE TITLE
Proxying Plausible through Vercel

### ISSUE THREAD

**Issue by marcusarnfast** [nuxt-modules/plausible#4]
Hi, awesome module!

But my questions is how would i intergrate Proxying Plausible through Vercel with this module
https://plausible.io/docs/proxy/guides/vercel

Thanks!

**Comment by johannschopplich** [comment]
Hey there, it seems like the [Plausible tracking library](https://github.com/plausible/plausible-tracker) doesn't support to customize the events API path, like the Plausible embedded `<script>` does. It solely lets you overwrite the API host location, which is also available within the Nuxt module configuration:

```ts
export default defineNuxtConfig({
  plausible: {
    apiHost: '',
  },
})
```

It won't let you add a proxy event path like `/stats/api/event` however, unfortunately. Feel free to open an issue over at [plausible-tracker](https://github.com/plausible/plausible-tracker). Thanks!
