### ISSUE TITLE
Exclude specific pages from being tracked

### ISSUE THREAD

**Issue by ymansurozer** [nuxt-modules/plausible#9]
Plausible allows excluding specific pages from being tracked. Is it possible to use that feature with this module? I did not see anything in the module options.

**Comment by Barbapapazes** [comment]
Hey @ymansurozer, is there a documentation page about this? 👀

I'm forking the plausible tracker and we could resolve this!

**Comment by ymansurozer** [comment]
Hey @Barbapapazes. There is no config for this as far as I can see. So I ended up using the original plausible-tracker library and creating a Nuxt plugin to watch the route and enable/disable page tracking per my needs.
